// build.mjs — parse resources/*.md into src/data.js (ESM module for Vite).
// Runs in CI and locally. No dependencies beyond Node stdlib.
import fs from "node:fs";
import path from "node:path";
import url from "node:url";
import { parseDirectory } from "./parse.mjs";

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), "..");
const RES_DIR = path.join(ROOT, "resources");
// map resource filename -> output category key (also used by the UI in this order)
const CATEGORIES = [
  ["component-libraries.md", "Component Libraries"],
  ["design-systems.md", "Design Systems"],
  ["design-inspiration.md", "Design Inspiration"],
  ["developer-tools.md", "Developer Tools"],
  ["prompts.md", "Prompts"],
];

function build() {
  const parsed = parseDirectory(RES_DIR);
  const data = {};
  for (const [file, key] of CATEGORIES) {
    const p = parsed[file];
    if (!p) throw new Error(`Missing resource file: ${file}`);
    const items = [];
    for (const g of p.groups) {
      for (const it of g.items) {
        items.push({
          name: it.name,
          url: it.url,
          ...(g.name !== "General" ? { group: g.name } : {}),
          ...(it.note ? { note: it.note } : {}),
        });
      }
    }
    data[key] = items;
  }
  const payload = `// Generated by scripts/build.mjs — do not edit.
export default ${JSON.stringify(data, null, 2)};\n`;
  // validate: no duplicate URLs across categories (case-trailing-slash normalized)
  const seen = new Map();
  for (const key of Object.keys(data)) {
    for (const it of data[key]) {
      const norm = it.url.replace(/\/+$/, "").toLowerCase();
      if (seen.has(norm)) {
        throw new Error(
          `Duplicate URL across categories: "${it.url}" in [${key}] and [${seen.get(norm)}]`,
        );
      }
      seen.set(norm, key);
    }
  }
  const outDir = path.join(ROOT, "src");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "data.js"), payload, "utf8");
  writeLlms(data);
  const total = Object.values(data).reduce((s, arr) => s + arr.length, 0);
  console.log(`Built src/data.js (${total} entries):`);
  for (const [file, key] of CATEGORIES) console.log(`  ${key}: ${data[key].length}`);
  return total;
}

// llms.txt (index) + llms-full.txt (all resources inline) for LLM/agent fetching.
function writeLlms(data) {
  const base = "https://design.ghuf.app";
  const index = [
    "# Curated Design",
    "",
    "> Curated directory of design resources: component libraries, design systems,",
    "> design inspiration, developer tools, and AI prompts. Each entry links straight",
    "> to the source. Full list with all entries: https://design.ghuf.app/llms-full.txt",
    "",
    "## Categories",
    "",
  ];
  const full = [
    "# Curated Design — full resource list",
    "",
    "Curated directory of design resources. Grouped by category. Each line is",
    "`[Name](url) — note`.",
    "",
  ];
  for (const key of Object.keys(data)) {
    const count = data[key].length;
    index.push(`- [${key}](${base}): ${count} resources`);
    full.push(`## ${key}`, "");
    for (const it of data[key]) {
      const note = it.note ? ` — ${it.note}` : "";
      full.push(`- [${it.name}](${it.url})${note}`);
    }
    full.push("");
  }
  fs.writeFileSync(path.join(ROOT, "public", "llms.txt"), index.join("\n"), "utf8");
  fs.writeFileSync(path.join(ROOT, "public", "llms-full.txt"), full.join("\n"), "utf8");
  console.log(`Wrote public/llms.txt (${index.length} lines), public/llms-full.txt (${full.length} lines)`);
}

export default build;

if (import.meta.url === url.pathToFileURL(process.argv[1]).href) {
  build();
}
